# Data Analysis

In [60]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [61]:
df = pd.read_excel('global_laptop_selling_data.xlsx')

In [62]:
df.head()

laptop_ID Company      Product   TypeName  Inches  \
0          1   Apple  MacBook Pro  Ultrabook    13.3   
1          2   Apple  Macbook Air  Ultrabook    13.3   
2          3      HP       250 G6   Notebook    15.6   
3          4   Apple  MacBook Pro  Ultrabook    15.4   
4          5   Apple  MacBook Pro  Ultrabook    13.3   

                     ScreenResolution                         Cpu   Ram  \
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8GB   
1                            1440x900        Intel Core i5 1.8GHz   8GB   
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8GB   
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16GB   
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8GB   

                Memory                           Gpu  OpSys  Weight  \
0            128GB SSD  Intel Iris Plus Graphics 640  macOS  1.37kg   
1  128GB Flash Storage        Intel HD Graphics 6000  macOS  1.34kg   
2            256GB SSD         Intel HD Graphics 620  No OS  1.86kg   
3            512GB SSD            AMD Radeon Pro 455  macOS  1.83kg   
4            256GB SSD  Intel Iris Plus Graphics 650  macOS  1.37kg   

   Price_euros  
0      1339.69  
1       898.94  
2       575.00  
3      2537.45  
4      1803.60

In [63]:
df.tail()

laptop_ID Company                              Product  \
1298       1316  Lenovo                       Yoga 500-14ISK   
1299       1317  Lenovo                       Yoga 900-13ISK   
1300       1318  Lenovo                   IdeaPad 100S-14IBR   
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon   
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)   

                TypeName  Inches                            ScreenResolution  \
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080   
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300            Notebook    14.0                                    1366x768   
1301            Notebook    15.6                                    1366x768   
1302            Notebook    15.6                                    1366x768   

                                       Cpu   Ram              Memory  \
1298            Intel Core i7 6500U 2.5GHz   4GB           128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB           512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB  64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB             1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB           500GB HDD   

                        Gpu       OpSys  Weight  Price_euros  
1298  Intel HD Graphics 520  Windows 10   1.8kg        638.0  
1299  Intel HD Graphics 520  Windows 10   1.3kg       1499.0  
1300      Intel HD Graphics  Windows 10   1.5kg        229.0  
1301     AMD Radeon R5 M330  Windows 10  2.19kg        764.0  
1302      Intel HD Graphics  Windows 10   2.2kg        369.0

In [64]:
df.shape

(1303, 13)

In [66]:
df.describe()

laptop_ID       Inches  Price_euros
count  1303.000000  1303.000000  1303.000000
mean    660.155794    15.017191  1123.686992
std     381.172104     1.426304   699.009043
min       1.000000    10.100000   174.000000
25%     331.500000    14.000000   599.000000
50%     659.000000    15.600000   977.000000
75%     990.500000    15.600000  1487.880000
max    1320.000000    18.400000  6099.000000

In [69]:
df.corr(numeric_only = True)

laptop_ID    Inches  Price_euros
laptop_ID     1.000000 -0.087796     0.067830
Inches       -0.087796  1.000000     0.068197
Price_euros   0.067830  0.068197     1.000000

# Data Cleaning 

In [70]:
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [71]:
df.dropna()

laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro   
1             2   Apple                          Macbook Air   
2             3      HP                               250 G6   
3             4   Apple                          MacBook Pro   
4             5   Apple                          MacBook Pro   
...         ...     ...                                  ...   
1298       1316  Lenovo                       Yoga 500-14ISK   
1299       1317  Lenovo                       Yoga 900-13ISK   
1300       1318  Lenovo                   IdeaPad 100S-14IBR   
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon   
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)   

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
1              Ultrabook    13.3                                    1440x900   
2               Notebook    15.6                           Full HD 1920x1080   
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800   
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
...                  ...     ...                                         ...   
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080   
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300            Notebook    14.0                                    1366x768   
1301            Notebook    15.6                                    1366x768   
1302            Notebook    15.6                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys  Weight  Price_euros  
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69  
1           Intel HD Graphics 6000       macOS  1.34kg       898.94  
2            Intel HD Graphics 620       No OS  1.86kg       575.00  
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45  
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00  
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00  
1300             Intel HD Graphics  Windows 10   1.5kg       229.00  
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00  
1302             Intel HD Graphics  Windows 10   2.2kg       369.00  

[1303 rows x 13 columns]

In [72]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [73]:
df.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [74]:
from pandas.core.dtypes.common import is_numeric_dtype

In [75]:
for col in df.columns:
    if is_numeric_dtype(df[col]):
        continue
    else:
        df[col] = le.fit_transform(df[col])

In [76]:
df.head()

laptop_ID  Company  Product  TypeName  Inches  ScreenResolution  Cpu  Ram  \
0          1        1      300         4    13.3                23   65    8   
1          2        1      301         4    13.3                 1   63    8   
2          3        7       50         3    15.6                 8   74    8   
3          4        1      300         4    15.4                25   85    1   
4          5        1      300         4    13.3                23   67    8   

   Memory  Gpu  OpSys  Weight  Price_euros  
0       4   56      8      38      1339.69  
1       2   50      8      35       898.94  
2      16   52      4      74       575.00  
3      29    8      8      71      2537.45  
4      16   57      8      38      1803.60

In [77]:
x=df.drop("laptop_ID",axis=1)

In [78]:
x.head()

Company  Product  TypeName  Inches  ScreenResolution  Cpu  Ram  Memory  \
0        1      300         4    13.3                23   65    8       4   
1        1      301         4    13.3                 1   63    8       2   
2        7       50         3    15.6                 8   74    8      16   
3        1      300         4    15.4                25   85    1      29   
4        1      300         4    13.3                23   67    8      16   

   Gpu  OpSys  Weight  Price_euros  
0   56      8      38      1339.69  
1   50      8      35       898.94  
2   52      4      74       575.00  
3    8      8      71      2537.45  
4   57      8      38      1803.60

In [79]:
y = df[["laptop_ID"]]

In [80]:
y.head()

laptop_ID
0          1
1          2
2          3
3          4
4          5

In [81]:
from sklearn.model_selection import train_test_split as tts

In [82]:
xtrain,xtest,ytrain,ytest=tts(x,y,test_size=0.3,random_state=45)

In [83]:
xtrain.head()

Company  Product  TypeName  Inches  ScreenResolution  Cpu  Ram  Memory  \
143        16      411         3    15.6                 0   68    5      26   
284         0       67         3    15.6                15  106    8      16   
599         4      350         5    15.6                 7  102    8      16   
102         4      240         3    15.6                 8   83    8      10   
1278        4      238         3    15.6                 0   34    3      26   

      Gpu  OpSys  Weight  Price_euros  
143    46      5     105        602.0  
284    94      5     166        951.0  
599   104      5      92       1763.0  
102     5      2     113        647.0  
1278   39      5     106        379.0

In [84]:
ytrain.head()

laptop_ID
143         146
284         289
599         606
102         105
1278       1296

In [85]:
xtest.head()

Company  Product  TypeName  Inches  ScreenResolution  Cpu  Ram  Memory  \
731         4      239         3    15.6                 0   74    0      10   
815        10      488         4    14.0                 8   97    8      16   
666         4      277         3    15.6                 8   74    8      10   
538         7      313         1    17.3                 8  102    0      10   
1166       10      471         3    15.6                15   74    8      16   

      Gpu  OpSys  Weight  Price_euros  
731    52      5     110        649.0  
815    52      5      34       1859.0  
666    52      5      92        955.0  
538    75      5     130       1799.0  
1166   52      5      83       1390.0

In [86]:
ytest.head()

laptop_ID
731         739
815         824
666         674
538         545
1166       1184

# Regression Techniques

In [87]:
from sklearn.linear_model import LinearRegression

In [88]:
reg=LinearRegression()

In [89]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [90]:
reg.predict([[4,8,12,16,15.6,17.3,14,13.3,12,13,27,28]])

array([[253.8193821]])

In [91]:
pred=reg.predict(xtest)
pred

array([[ 595.88119356],
       [ 702.21334211],
       [ 605.16774114],
       [ 629.75336137],
       [ 670.73080576],
       [ 818.42484771],
       [ 688.04896289],
       [1047.37553493],
       [ 630.95817493],
       [ 613.6961716 ],
       [ 486.21883688],
       [ 832.73704728],
       [ 617.39510638],
       [ 675.93426872],
       [ 721.33959427],
       [ 621.90198627],
       [ 677.4450218 ],
       [ 800.46659217],
       [ 752.91370644],
       [ 827.09120114],
       [ 820.835873  ],
       [ 648.33582963],
       [ 648.42163325],
       [ 465.21331685],
       [ 685.49305698],
       [ 810.61630898],
       [ 674.50531473],
       [ 606.46616801],
       [ 694.62926999],
       [ 766.52880004],
       [ 567.14548374],
       [ 647.06393152],
       [ 617.20461506],
       [ 551.62653232],
       [ 634.61421823],
       [ 728.43767184],
       [ 703.2277044 ],
       [ 707.69724825],
       [ 655.09157442],
       [ 624.4077746 ],
       [ 708.41043258],
       [ 625.238

In [92]:
df["Predicted Result"]= reg.predict(x)

In [93]:
df.head()

laptop_ID  Company  Product  TypeName  Inches  ScreenResolution  Cpu  Ram  \
0          1        1      300         4    13.3                23   65    8   
1          2        1      301         4    13.3                 1   63    8   
2          3        7       50         3    15.6                 8   74    8   
3          4        1      300         4    15.4                25   85    1   
4          5        1      300         4    13.3                23   67    8   

   Memory  Gpu  OpSys  Weight  Price_euros  Predicted Result  
0       4   56      8      38      1339.69        582.540168  
1       2   50      8      35       898.94        650.757496  
2      16   52      4      74       575.00        560.953537  
3      29    8      8      71      2537.45        558.725216  
4      16   57      8      38      1803.60        624.458824

In [94]:
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error

In [95]:
mse = mean_squared_error(ytest,pred)

In [96]:
mse

130471.61554264637

In [97]:
mae = mean_absolute_error(ytest,pred)
mae

306.777012969117

In [98]:
accuracy = r2_score(ytest,pred)

In [99]:
accuracy

0.058509867071060984

In [100]:
m = reg.coef_
m

array([[  8.08194605,   0.09800259, -28.87469646, -47.06461373,
         -4.78951433,  -1.8677368 ,   4.38198337,   0.50068547,
         -0.1155018 ,  -0.7563216 ,   0.96690844,   0.08570931]])

In [101]:
c = reg.intercept_
c

array([1341.97095462])

In [102]:
from sklearn.neighbors import KNeighborsRegressor

In [103]:
ne = KNeighborsRegressor(n_neighbors=10)

In [104]:
ne.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=10)

In [105]:
ne.predict([[4,8,12,16,15.6,17.3,14,13.3,12,13,27,28]])

array([[555.4]])

In [106]:
kntest = ne.predict(xtest)

In [107]:
kntest

array([[ 562.7],
       [ 708.7],
       [ 794.1],
       [ 638.3],
       [ 637.2],
       [ 850.8],
       [ 823.1],
       [ 837.1],
       [ 763. ],
       [ 898.9],
       [ 679.7],
       [ 619.1],
       [ 481.5],
       [ 601.1],
       [ 718. ],
       [ 970.7],
       [ 799.7],
       [ 698. ],
       [ 662.2],
       [ 643.8],
       [ 852.4],
       [ 639.6],
       [ 446.7],
       [ 714.5],
       [ 561.4],
       [ 809. ],
       [ 661.8],
       [ 662.3],
       [ 497.5],
       [ 644.1],
       [ 551.4],
       [ 880.5],
       [ 689.5],
       [ 634.4],
       [ 686. ],
       [ 971.8],
       [ 778.4],
       [ 490.3],
       [1061.4],
       [ 709.3],
       [ 631.3],
       [ 590. ],
       [ 699.2],
       [ 695.9],
       [ 608.5],
       [ 545.8],
       [ 601.6],
       [ 612.7],
       [ 609. ],
       [ 474.4],
       [ 704.6],
       [ 553.4],
       [ 596.7],
       [ 590.3],
       [ 654.1],
       [ 808.9],
       [ 992.2],
       [ 714.9],
       [ 935.1

In [108]:
accuracy = r2_score(ytest,kntest)

In [109]:
accuracy

-0.042576948054824815

In [110]:
mse = mean_squared_error(ytest,kntest)

In [111]:
mse

144480.21703324807

In [112]:
mae = mean_absolute_error(ytest,kntest)

In [113]:
mae

320.75805626598464

In [114]:
from sklearn.svm import SVR #support vector Regression

In [115]:
svm = SVR(kernel='linear')

In [116]:
svm.fit(xtrain,ytrain)

SVR(kernel='linear')

In [117]:
svm.score(xtest,ytest)

0.021938065369910387

In [118]:
svm2 = SVR(kernel='rbf')

In [119]:
svm2.fit(xtrain,ytrain)

SVR()

In [120]:
svm2.score(xtest,ytest)

0.0033538007712771156